### ISSUE TITLE
JetBrains: Cody is not remembering user's question when asking follow up question after opening from Chat history.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1090]
### Installation Information

Plugin version: `5.4.5-nightly`
IDE version: `IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains PyCharm editor
2. User is already logged in to Cody using Pro account
3. Start a new chat
4. Send message similar to "my favorite car is Supra"
5. Wait for Cody to finish responding
6. Close IDE
7. Launch IDE and open previous conversation from "Chat History"
8. Ask "What is my favorite car?"

### Observed behavior:
Cody is not remembering my questions and chat responsed

### Expected behavior

Cody should remember my questions and previous chat responses.

### Additional context

**Video link:**

1. https://drive.google.com/file/d/1IsTapiZ0ihTGbfZMba9_srtMQds5Rb2h/view?usp=drive_link
2. https://drive.google.com/file/d/1HHdY0NNKLUHFaycHg5z06J7Onr-ZERpz/view?usp=drive_link

**Comment by mkondratek** [comment]
<img width="507" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/3b01b96a-b0c5-4496-9247-71f512a63352">

hmmm, it works for me. 

Please note that based on the given videos Cody DOES remember the context but the response is very indirect. This issue seems to be unrelated to jetbrains plugin itself (it is probably related to cody or a llm). I am going to close this one and start a thread on Slack.
