### ISSUE TITLE
bug: Hint text in chatting text field box not visible in IDE dark mode

### ISSUE THREAD

**Issue by itstanany** [sourcegraph/jetbrains#1316]
### Cody Version

5.5.5

### IDE Information

Android Studio Iguana | 2023.2.1 Patch 2
Build #AI-232.10300.40.2321.11668458, built on April 4, 2024
Runtime version: 17.0.9+0--11185874 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    idea.ignore.disabled.plugins=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.godwin.json.parser (1.7.1)
    PlantUML integration (7.8.1-IJ2023.2)
    com.intellij.marketplace (232.10300.41)
    com.facebook.ktfmt_idea_plugin (1.1.0.47)
    Dart (232.10313)
    com.localizely.flutter-intl (1.18.4-2023.2)
    wu.seal.tool.jsontokotlin (3.7.4)
    no.hvl.tk.visualDebugger (2.1.3)
    com.aegamesi.java_visualizer.plugin (2.2.1)
    com.bloc.intellij_generator_plugin (4.0.0)
    org.exbin.deltahex.intellij (0.2.10.1)
    com.herbert.george.flutter-snippets (2.0.0-stable-1)
    idea.plugin.protoeditor (232.10300.51)
    com.zll.format (2.2)
    Docker (232.10300.41)
    izhangzhihao.rainbow.brackets (2023.3.7)
    com.nbadal.ktlint (0.22.0)
    com.vv.adbuninstall (1.1.4)
    com.suusan2go.kotlin-fill-class (1.0.23)
    com.sourcegraph.jetbrains (5.5.5)
    io.flutter (78.4.1)
    de.mariushoefler.flutter_enhancement_suite (1.7.1)
    com.ruiyu.ruiyu (5.1.5)
    com.kn.diagrams.generator.generator (2022.2.0)

### Describe the bug

OPening chat box in dark mode, the hint text about how to add files to context not visible

### Expected behavior

Hine text is expected to be visible like in liight mode

**Comment by dominiccooney** [comment]
I tried this with One Dark and Darcula on macOS and the hint text is visible for me, contrast ratio around 4.5:1.

@itstanany what specific theme are you using?

@mkondratek  would setting DarculaTextAreaUI directly cause this? Why don't we simply leave the default alone?

**Comment by itstanany** [comment]
@dominiccooney 
Default Intelliji Dark theme. I use `sync with OS` theme setting in intelliji

**Comment by mkondratek** [comment]
<img width="476" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/4f604494-b5c2-4e80-8cd1-ebc6f2a8aa51">
<img width="471" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/4751f0ba-f858-4234-aa07-aa8071ad6e20">

hello 👋 here is how it looks like for me ☝️ the hint text is visible in both cases (I changed the settings to `sync with OS` and changed the os theme).

@dominiccooney, I tried to use `BasicTextAreaUI` instead of `DarculaTextAreaUI` but I see no difference: 
<img width="480" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/32d2863e-ac17-4130-b733-3262d6065e72">
<img width="478" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/60d5ae95-18a7-4227-9cb9-a90cc8040f0b">

@itstanany, can you tell something more? can you attach a screenshot? maybe the hint text appears after restarting your IDE?
