### ISSUE TITLE
JetBrains: Local chat context is not available for context in enterprise account

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1353]
### Cody Version

v5.5.6-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (5.5.6-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Check the Cody Chat context

### Observed behavior:

Local project chat context is missing for enterprise user.

### Expected behavior

Local project chat context should be there along with remote repo.

### Additional context

**Screenshots:**

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/b00a8e4d-85c1-456b-ae74-7ff9b591d63d/b926c51c-9728-4239-9b5d-7235cd2b8eca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9iMDBhOGU0ZC04NWMxLTQ1NmItYWU3NC03ZmY5YjU5MWQ2M2QvYjkyNmM1MWMtOTcyOC00MjM5LTliNWQtNzIzNWNkMmI4ZWNhIiwiaWF0IjoxNzE3NDUyMjc0LCJleHAiOjMzMjg4MDEyMjc0fQ.wGen8nmYYOvK9390aeDkm5mX3ib0Mye01zjyoNifjOY)

![image (1)](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/05e2d3dd-1cf6-4e62-b72c-f6c9c56554e9/4d305ec3-149f-4bb6-a60e-ddfeda181e7e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8wNWUyZDNkZC0xY2Y2LTRlNjItYjcyYy1mNmM5YzU2NTU0ZTkvNGQzMDVlYzMtMTQ5Zi00YmI2LWE2MGUtZGRmZWRhMTgxZTdlIiwiaWF0IjoxNzE3NDUyMjc0LCJleHAiOjMzMjg4MDEyMjc0fQ.9c9aDrh-JPQ1e8ly6--7FzOC-CXgMl_DvnHDGYQseiI)

**Comment by dominiccooney** [comment]
This is working as intended. The new UX design does not have a checkbox for local context. Screenshot from Figma:

![Screenshot 2024-04-30 at 16 39 30](https://github.com/sourcegraph/jetbrains/assets/55120/c6c769c6-a6b2-4258-9832-5d5ac8ad04d6)

You will notice the product has "Repositories" instead of "Repos" with a checkbox. That is to match VSCode which doesn't have a global on/off for all remote repositories:

![Screenshot 2024-04-30 at 16 42 06](https://github.com/sourcegraph/jetbrains/assets/55120/2af6eeb5-3724-47c7-8211-be0c435ed198)

The plan of record for the treeview language w/ @danielmarquespt is in #1322 and the screenshot in the bug report matches the tree view language in that issue.
