### ISSUE TITLE
JetBrains: Repositories marked as "Not found" when user add more than 10 repo.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1693]
### Cody Version

v5.5.18-nightly

### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
ide.experimental.ui=true
Non-Bundled Plugins:
com.sourcegraph.jetbrains (5.5.18-nightly)

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Add more than 10 remote repo from chat context

### Observed behavior:
Any repo after 10th one is showing as "Not found" but deselecting other and selecting this will eventually added.

### Expected behavior

This is confusing as marking repo as "Not found" because it is exceeding maximum repo limit.

### Additional context

**Video link:**

https://drive.google.com/file/d/1aG7tJ1_xvHYdPX7jBYFDsH5MaTRCIoUK/view?usp=drive_link

**Comment by dominiccooney** [comment]
I know exactly why this happens, the Agent caps the returned repository list to 10. So the impact of this is low:

- only happens if you add more than 10 repos
- only happens if your other repo resolutions are not cached, that is, you need to add more than 10 repos at once
- workaround is to edit the repo list and resubmit

So this should not block GA, and it is probably a P2.

The plan is to remove this component, so we will probably never fix this.
