### ISSUE TITLE
Spurious "Cody is disabled" under low memory conditions

### ISSUE THREAD

**Issue by odisseus** [sourcegraph/jetbrains#1729]
### Cody Version

6.0.3-nightly

### IDE Information

CLion 2024.1.2
Build #CL-241.17011.124, built on May 28, 2024
Licensed to Virtus Lab sp. z o.o. / Myroslav Golub
You have a perpetual fallback license for this version.
Subscription is active until April 12, 2025.
Runtime version: 17.0.11+1-b1207.24 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.7.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Metal Rendering is ON
Registry:
  actionSystem.update.actions.warn.dataRules.on.edt=false
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.slow.operations.assertion=false
  cidr.enable.testRunLineMarkers.clangCatchTestFrameworkSupport=false
  cidr.enable.testRunLineMarkers.clangDoctestTestFrameworkSupport=false
  cidr.enable.testRunLineMarkers.clangBoostTestFrameworkSupport=false
Non-Bundled Plugins:
  com.google.idea.bazel.clwb (2024.05.07.0.1-api-version-241)
  com.sourcegraph.jetbrains (6.0.3-nightly)

### Describe the bug

I have loaded a large C++ project into CLion with only 2048 MB of heap memory (which is too little for reliable operation). Whenever I tried to use inline edits, I was getting a "Cody is disabled" notification, even though I hadn't configured codyignore at all.

### Expected behavior

While it is no surprise that the Cody plugin did not work properly (and eventually the whole IDE froze), those notifications were totally misleading.

**Comment by dominiccooney** [comment]
This is probably Context Filters "failing closed" because we aren't getting responses from context filters fast enough. TBH, making Cody + IntelliJ work in 2 GB heap is going to be very tough.

**Comment by chenkc805** [comment]
Some questions here:

* This user looks to be a PLG user, since they mention codyignore, so would it be more accurate to say "this is probably codyignore 'failing closed' "?
* Is it common for normal PLG users to work with only 2 GB of heap memory? 

Regardless, I think the request here is mainly to update the **error notification.** So let's move forward with:

* if we detect that Cody is running into performance issues (low RAM, low CPU, etc.), show an error that says something of the nature:
  * "Cody error: we're detecting that we're running into performance issues with your editor. Please restart your editor or check background running tasks to ensure Cody works properly." or something like that. 
  * @dominic.cooney What do you think?

**Comment by chenkc805** [comment]
Assigning to @dominic.cooney to get your feedback and resize based on just updated the error

**Comment by dominiccooney** [comment]
> * This user looks to be a PLG user, since they mention codyignore, so would it be more accurate to say "this is probably codyignore 'failing closed' "?

The "Cody is disabled" error message could be Cody was slow to start because the IDE was thrashing under the low memory limit ("Cody is disabled or still starting up"), or Context Filters  ("Cody is disabled on this file") because we are being conservative. If we've started up and you're logged into dotcom, we don't display that message.
