### ISSUE TITLE
JetBrains: Alt+\ is not triggering autocompletion, instead opening File menu

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1840]
### IDE Information

PyCharm 2023.3.4 (Community Edition)
Build #PC-233.14475.56, built on February 26, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.10-nightly)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with a Pro account
3. Open any source code and start coding
4. Hit `Alt + \` to trigger Cody autocomplete

### Observed behavior:
Cody autocomplete will not be triggered and instead file menu opened.

### Expected behavior:
Cody autocomplete should be triggered correctly.

### Additional context

**Video link:**

https://drive.google.com/file/d/1-qkBah4X1r--AsMVzkGVPxsJKtJwJkLr/view?usp=drive_link

**Comment by mkondratek** [comment]
~Works fine on my macOS machine. I have no access to anything running Windows. Can someone else check this one? 🙏~

**Comment by pkukielka** [comment]
It was changed by @steveyegge due to new keymap proposed by @danielmarquespt : https://linear.app/sourcegraph/document/keyboard-shortcuts-for-cody-on-jetbrains-2f8747a22530
@taylorsperry I think some problem there might be that we do not notify users about that change in any way, and otherwise this shortcut is hard to discover. We need to decide if we just go with it, or do we want to improve it somehow.

**Comment by jay-fibi** [comment]
@mkondratek I am on macOS with PyCharm and the `option + \` seems broken. It prints « character instead of triggering autocomplete. 
cc @taylorsperry @kalanchan It was working with earlier releases.

**Comment by kalanchan** [comment]
i believe we fixed this, please re-file if it's still a problem
