### ISSUE TITLE
PRD: [JB] Users can export chats

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#227]
### Description:

As a user, I want to see and export my Cody chat history so that I can understand/share the prompts and responses from my interactions with Cody. 

### Objectives:

Make it easy to see and share the prompts and responses from my interactions with Cody. 

```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/sourcegraph/jetbrains/issues/405
```

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit)

**Comment by exigow** [comment]
Oh, I just noticed that this issue isn't scheduled for the February release (change was made 4 days ago). However, for some reason, this issue ended up on our board (https://github.com/orgs/sourcegraph/projects/381/views/15, likely due to imprecise query). 

Unassigning.

**Comment by exigow** [comment]
BTW Cody's history is stored in the `cody_history.xml` configuration file so it's not JSON. If this task is solely for our debugging purposes, I don't see the point in writing specific code that exports to the same JSON schema as the one presented in VS Code. If a user encounters an error and sends us that XML, it will be totally enough (or even better, because we will be able to easily reproduce issues locally by simply replacing this file with our local config).

@taylorsperry, do I understand this issue correctly? What's the motivation for this user story? Would it be okay if we provide export options for original XML files?
