### ISSUE TITLE
PRD: Fire telemetry when users see / interact with upsell and abuse messages

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/jetbrains#228]
### Description:

Spec here in "Dec GA Telemetry" tab: https://docs.google.com/spreadsheets/d/1QXnrHkgGLXdbfHEhI_VjtDTy-mCtnK1qri3IMQu7rNk/edit#gid=1704312181&range=3:12

### Design Tasks:

```[tasklist]
### Design Tasks
- [ ] Add a draft title or issue reference here
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
- [ ] Add a draft title or issue reference here
```

### Related Docs:

- [PRD: Your-Title]()

**Comment by chenkc805** [comment]
Hey @olafurpg , happy new year! When do you think we can get started on this?

**Comment by olafurpg** [comment]
@chenkc805 after a scoping exercise last week, we marked the delivery of this as happening after Feb GA since this issue has P1 and we only have bandwidth to deal with P0s. Do you want to bump this into P0?

**Comment by chenkc805** [comment]
I would like to get this in before Feb release since JetBrains will be GA'ing and Jetbrains now makes up a non-trivial amount of users. Updating to P0

**Comment by olafurpg** [comment]
@chenkc805 thanks!

@Sa1to Assigning this to you alongside other PLG-related issues. I've tentatively assigned it for the iteration ending Feb 5th but the sooner we can land this the better!

**Comment by taylorsperry** [comment]
I agree that telemetry is super important, but stability issues definitely take priority (we already know that the metrics will be bad if the user experience stinks 😄). I think we should prioritize user facing issues like stability and feature parity (we're already making some tough scope cuts for GA) and add telemetry either during feature freeze or as an immediate follow-up to GA. If you disagree, @chenkc805, we can run it by Chris to help us make the call.

**Comment by chenkc805** [comment]
Agree with @taylorsperry

**Comment by olafurpg** [comment]
Based on the conversation above, marking this as a P1 since it's not critical for the launch date and tentatively assigning it to the iteration February 20 - March 4.

For the person who ends up working on this, the following code examples from the VSC extension show where these events are submitted https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/cody%24+CodyVSCodeExtension:upsellUsageLimitCTA+or+CodyVSCodeExtension:abuseUsageLimitCTA&patternType=lucky&sm=1

I also started a Slack thread on the v1->v2 migration for telemetry since it's unclear to me whether these events should be submitted as v1 or v2. The VSC implementation uses v1 events, which are marked as deprecated. https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1706531221801669
