### ISSUE TITLE
BUG: Sourcegraph Link Defaults To Master Branch Instead Of Currently Checked Out Local

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/jetbrains#3]
- **Platform information:** JetBrains Cody Extension Version 3.4.1

#### Steps to reproduce:

1. Right click into any file with the extension installed and choose the Copy Sourcegraph File Link 
2. The link will be for the current file but not for the currently checked out branch.

#### Expected behavior:

The Sourcegraph link would be for the currently checked out branch.

#### Actual behavior:

The Sourcegraph link is currently for the master branch.

**Comment by alexAtSourcegraph** [comment]
Currently working on this.

**Comment by mkondratek** [comment]
I took a look at this one. The problem seems to lay somewhere in:
https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fjetbrains&branch=main&file=src%2Fmain%2Fjava%2Fcom%2Fsourcegraph%2Fvcs%2FRepoUtil.java&start_row=28&start_col=0&end_row=77&end_col=0

It looks like the condition there make it **always default branch**.
