### ISSUE TITLE
Export chat history to JSON & CSV

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#405]
Mimic behavior in VSC added by [this PR](https://github.com/sourcegraph/cody/pull/829).

**Comment by exigow** [comment]
@taylorsperry, just to confirm: is this issue scheduled for the Feb release? The pfp-jetbrains-feb label from the metioned (https://github.com/sourcegraph/jetbrains/issues/227) production issue has been removed.

**Comment by olafurpg** [comment]
The pfp-jetbrains-feb label should probably not be on this issue because it didn't have the `GA:` prefix. I did my best to correctly assign the label but this issue seems like an oversight

**Comment by kalanchan** [comment]
@mkondratek @danielmarquespt will have designs ready for you

**Comment by danielmarquespt** [comment]
https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/JetBrains?type=design&node-id=751%3A13941&mode=design&t=wJgYDLeIHbNliJ0L-1

Since this is mostly for debug/advanced purposes and exports the whole history (I originally thought it was per chat) I moved the button to the bottom part of the history panel

There is also a version that provides the UX for a per-chat export, if needed
