### ISSUE TITLE
JetBrains: duplicate `CodyInstalled` events

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#43]
Context https://sourcegraph.slack.com/archives/C059N5FRYG3/p1697568648010619

Here is where we log the `CodyInstalled` event

https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/blob/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java?L21

We trigger it on

- installation
- user changes server
- user changes access token

One possible resolution step is to persist which server URL has already received this event so that we never send it again for the same server URL.

**Comment by akalia25** [comment]
Thanks for creating this ticket! It is also important to note that this event has been firing multiple times at the **exact same timestamp**, so it might be possible that the installed event is continuously firing during one of those triggers? If you need any data support, do let me know, and thanks for taking this on!

**Comment by olafurpg** [comment]
@akalia25 Thank you! We are unable to reproduce this locally making it difficult to fix the problem. We are keeping this issue on the board for now but de-prioritizing it since have other items that need more attention. Feel free to bump this if it's an important issue to fix.

**Comment by kelsey-brown** [comment]
Hey @olafurpg, following up here - I originally would have agreed with your assessment that this isn't a top priority, since we're de-duping Cody installs on the analytics side by counting daily unique users who fire this event. But we recently realized that CodyInstalled is firing for the same user _across_ days as well. We're de-duping within days, but not across days (so we're still over-counting installs).

Any chance you can bump this up on the priority list? If not, we can  go ahead and add in some transformations on our end to weed out the duplicates as a band-aid fix, but ideally I'd like to get this fixed in the logging.

**Comment by dadlerj** [comment]
I suspect that there are two different issues here. 

One is that we're logging CodyInstalled on settings changes (server endpoint and access tokens), which hopefully my PR linked above will fix.

The other is what @akalia25 talks about here:

>It is also important to note that this event has been firing multiple times at the exact same timestamp, so it might be possible that the installed event is continuously firing during one of those triggers?

Which is very weird. Clearly users aren't changing their server endpoint multiple times at once. Let's see if this continues after the fix above is merged.

**Comment by dadlerj** [comment]
@kelsey-brown @akalia25 are you aware of any existing event names from VS Code that I should replicate in JetBrains for config changes? I've made up new ones there, but want to be consistent if I can CC @Strum355

**Comment by kelsey-brown** [comment]
Here's what I could find in our tables that looked relevant, but it doesn't look like any of these events are actually firing anymore (most haven't fired since November) so if you'd prefer to change the names I think that's fine 👍 

`CodyVSCodeExtension:codyDeleteAccessToken:clicked`
`CodyVSCodeExtension:codySetAccessToken:clicked`
`CodyVSCodeExtension:updateEndpoint:clicked`

**Comment by dadlerj** [comment]
Thanks! There's always a subtle difference in choosing between the user action ("button clicked") and the underlying effect ("setting changed"). 

But I agree, the fact that these aren't in use makes me comfortable introducing new event names here.

**Comment by dadlerj** [comment]
@akalia25 @kelsey-brown if we continue to see the multiple events with the same timestamp let me know and we can reopen (or open a new issue!)

**Comment by kelsey-brown** [comment]
Hey team - re-opening this thread because unfortunately we think that CodyInstalled is still being logged on non-install events somehow. The reason we think that is because we're still seeing a lot of users firing CodyInstalled repeatedly across multiple days. If you look at our [daily cody installs on jetbrains broken out by first-time installers vs repeat installers](https://redash.sgdev.org/queries/418/source#872), it looks like most of the installs on any given day are coming from users who have already installed cody on jetbrains previously. I'd expect this to happen on occasion (maybe a user uninstalled and redownloaded, or something along those lines) but the fact that it's happening repeatedly to me makes it seem like something is broken here. 

Another reason I suspect something is off is that we’re seeing CodyInstalled events fire on non-dotcom endpoints - because install occurs before the user can update their endpoint, I’d expect most if not all install events to occur on dotcom. 

We'll keep digging on our end to see if we can uncover any more clues about what might be going on here but I wanted to re-open this ticket to flag this for your team as well if you have any ideas about what could be the cause here. 


Edit: I do think part of the reason this is continuing is because some users haven't upgraded yet, but I don't think it's the whole story... I would have expected this to start improving at least marginally as users upgrade, but we haven't seen that yet

cc @dadlerj and @chenkc805

**Comment by kelsey-brown** [comment]
@taylorsperry just realized you're not on this ticket, so flagging this for you for prioritization purposes. TLDR is that CodyInstalled events are being logged on non-install actions. What we haven't been able to figure out is _where_ exactly this could be happening, we just have a lot of evidence (laid out above) to suggest that that is the case. The metrics affected by this are our JetBrains daily install numbers and funnel conversion metrics. I know you guys have a lot going on so I'm running down ways to get around this on our end to get to accurate numbers in the meantime!

**Comment by chenkc805** [comment]
Hey @taylorsperry , 

Assigning to you so this doesn't fall through the cracks. I know it's been a while since we've gotten to this ticket but I think we should prioritize this before GA. Install metrics are super important for a bunch of reasons (looking at new users, understanding retention, etc.) and if they aren't being logged correctly it throws off our understanding of how JetBrains as an IDE is doing.
