### ISSUE TITLE
Issues reported with "Open GitHub Issue" have missing "bug" labels

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#645]
Very strange because all Cody JetBrains version with this feature has a code that adds the "bug" label (it's just adding `?labels=bug` to URL). This auto-labeling is necessary because we want to filter this issues.

I tried to reproduce it just now and it's working fine:

![Image](https://github.com/sourcegraph/jetbrains/assets/5013708/500e9499-4b5f-49e9-b9d6-b2b43fa7430e)

Maybe users outside the organization can't add labels?

**Comment by taylorsperry** [comment]
@kalanchan is this something you can take a look at? If you look at the "To triage" view of the board and scroll to the bottom, it seems there are quite a few issues that are being submitted via the bug template (they have the prefix "bug:") but aren't getting the label added correctly. 🤔

**Comment by mkondratek** [comment]
Reporting "Open GitHub Issue" works fine for me. The label is there. If it was missing for some issue the reporter likely removed it. 

@taylorsperry feel free to close this issue unless we want to cover something else here.

**Comment by exigow** [comment]
@mkondratek, this works for me too, but for some reason, errors reported by external users do not have this label and we have to add this manually. That's the whole point of this issue. 

I highly doubt that all external users are removing this label intentionally.

**Comment by pkukielka** [comment]
One more thing when checking that:

I think we should make description of the bug required (not possible to send error report without it).
Many user just hammer this button few times in a row.
We should add text describing what we would like to see (reproduction, or at lest description of how the issue was triggered in the first place) and also ask user to attach log later if possible (as it will expedite issue resolution).
