### ISSUE TITLE
JebBrain: There is no validation when adding same repo multiple times.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#659]
### Installation Information

Plugin version: `5.3.27-nightly`
IDE version: `IC-233.14015.106`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Enterprise subscription
3. Click [+] button in the context panel and type sourcegraph repo url [github.com/sourcegraph/sourcegraph](url)
4. Hit "Add" button
5. Repeat step-3 and step-4 multiple times

**Observed behavior:**
It allows user to add same repo multiple times

### Expected behavior

There should be some validation and not allow user to add duplicate repo.

### Additional context (logs, images, etc)

Video link:

https://drive.google.com/file/d/1XYIA2b1T3qTLvifLN_r3k0Jndi-TD8Hp/view?usp=drive_link

**Comment by taylorsperry** [comment]
Thanks, Jay, good catch! Does anything break when you add the same repo more than once?

**Comment by jay-fibi** [comment]
Nope, it just allows me to add the same repo. If I add same repo 5 times, it shows they all are added but when I hit "New Chat", there is only one shown.

**Comment by mkondratek** [comment]
FYI: since https://github.com/sourcegraph/jetbrains/pull/646 the duplicated entry does not appear in the list. 

Let's keep this issue open for now - the changes have not been released yet. 

Additionally I opened https://github.com/sourcegraph/jetbrains/pull/763 - we will have the proper validation in the first place.
