### ISSUE TITLE
JetBrains: There is a typo in LLM name for enterprise vs Pro user.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#691]
### Installation Information

Plugin version: `5.3.27`
IDE version: `IC-233.14015.106`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. Login to Cody with Pro subscription
3. Remove the account
4. Login to Cody with Enterprise subscription

**Observed behavior:**
There is a typo in LLM name "Cloude 2 by Anthropic" is shown for Enterprise and "Cloude 2.0 by Anthropic" is shown for Pro 

### Expected behavior

The typo should be fixed for LLM name.

### Additional context (logs, images, etc)

**Screenshots:**

<img width="426" alt="Screenshot 2024-02-16 at 10 36 21 PM" src="https://github.com/sourcegraph/jetbrains/assets/158482423/f354f595-0879-453a-a954-64a4dade1e91">
<img width="417" alt="Screenshot 2024-02-16 at 10 36 50 PM" src="https://github.com/sourcegraph/jetbrains/assets/158482423/4a156d64-3666-4290-9abe-35736a9b4a54">

**Comment by taylorsperry** [comment]
@jay-fibi I see "Claude" spelled correctly in both screenshots. Am I looking in the wrong spot?

**Comment by jay-fibi** [comment]
@taylorsperry the typo is `Claude 2` vs `Claude 2.0`

**Comment by mkondratek** [comment]
#753 will fix this one

**Comment by mkondratek** [comment]
A note here. My changes (#753) are going to remove the hardcoded values from jetbrains and depend on the agent's response. Presently, for `sourcegraph.sourcegraph.com` is see the following result:

```
[Trace - 09:45:24 PM] Sending request 'chat/models - (20)'
Params: {
  "id": "3d5d509e-721a-4756-82c2-f396dbc7d9cc"
}


[Trace - 09:45:24 PM] Received response 'chat/models - (20)' in 0ms
Result: {
  "models": [
    {
      "default": true,
      "codyProOnly": false,
      "provider": "Anthropic",
      "title": "claude 2",
      "model": "anthropic/claude-2"
    }
  ]
}
Error: null
```

That will be displayed as `claude 2 by Anthropic`. 

So basically I moved the problem from JetBrains to the agent 😅 

My thinking is this issue is a rather low priority however to fix it we need to know more:
can we change that title? how do we define the models? is it in GraphQL? is it instance-dependent?
