### ISSUE TITLE
JetBrains: agent isn't shut down on exit

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/jetbrains#8]
Noticed a large number of `cody-agentXXXXXX` processes running.  

Details:
- version: 3.4.1
- os: mac 13.4.1, 
- editor: IntelliJ CE

Steps to reproduce:

- Reboot 
- Open Activity monitor verify no cody-agent processes
- Start IntelliJ open project verify in activity monitor 1 `cody-agentXYZ` process
- Exit IntelliJ - see `cody-agentXYZ` process remains active
- Start IntelliJ open a project - see there are now 2 `cody-agentXYZ` processes

Expected behavior:
Exiting editor should terminate the cody agent process.

**Comment by mkondratek** [comment]
Wow, I saw a similar thing yesterday. It happened after I moved to the new jetbrains repo and wanted to `runIde`. I thought I messed smth up, my Macbook crashed due to lack of memory, and everything started to work as usual after reboot. I am good now (no performance issues). However, I just noticed I have 7 agents running.
