### ISSUE TITLE
JetBrains: Cody is giving wrong answer for remote repo when more than one repo are added.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#890]
### Installation Information

Plugin version: `5.3.1544-nightly`
IDE version: `IC-233.14015.106`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Enterprise subscription
3. Open Cody and ask question "what is squirrel?" and verify that it will answer you about the animal
4. Add different remote repo from [https://github.com/orgs/sourcegraph/repositories](https://github.com/orgs/sourcegraph/repositories ) URL
5. Add this specific remote repo [github.com/sourcegraph/sourcegraph](github.com/sourcegraph/sourcegraph)
6. Ask Cody "what is squirrel?" and verify that it will answer you about the animal
7. Remove all other repo added from step-4 and keep only [github.com/sourcegraph/sourcegraph](github.com/sourcegraph/sourcegraph)
8. Ask Cody "what is squirrel?" and verify that this time it will describe you an HTTP server, NOT animal.

**Observed behavior:**
When more than one remote repo are added then Cody is not recognising the context and giving wrong answer

### Expected behavior

Cody should answer correctly in the presence of multiple repo.

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1AQAVRLvtdqNQO6tz6TkJS_qBsAgjwSUO/view?usp=drive_link

**Comment by pkukielka** [comment]
Hey @jay-fibi, could you try to retest without `sourcegraph/jetbrains` repo on that list?
What happens there is we added testing steps in our [Testing guide](https://github.com/sourcegraph/jetbrains/blob/main/TESTING.md#freepro-accounts) which covers exactly that scenario, and mentions squirrel tests. Assistant is able to read that file, and it messes the result :)
You can actually notice this when you will check context used for giving the reply:

![image](https://github.com/sourcegraph/jetbrains/assets/1519649/f3877ddb-731f-42e8-8ad8-efff9c16e11a)

So, it's not a bug, it happens just because assistant gets conflicting context.
